let dados = [
    {
        nome: 'Fortnite',
        descricao: 'Fortnite é um jogo eletrônico multijogador online extremamente popular, desenvolvido pela Epic Games. Ele oferece diferentes modos de jogo, mas o mais conhecido é o Battle Royale, onde até 100 jogadores são lançados de um ônibus em uma ilha e precisam lutar pela sobrevivência, a ideia principal é simples: ser o último jogador em pé. Para isso, os jogadores precisam encontrar armas, materiais de construção e itens de cura espalhados pelo mapa, enquanto a área jogável se reduz gradualmente, forçando os jogadores a se enfrentarem em espaços cada vez menores.',
        link: 'https://pt.wikipedia.org/wiki/Fortnite_Battle_Royale',
        loja: 'https://store.epicgames.com/pt-BR/p/fortnite',
        anoLancamento: '2017',
        tags: 'Battle Royale Free-to-Play Cross-Play Cultura Pop Evolução Constante ',
    },
    {
        nome: 'League of Legends',
        descricao: 'League of Legends (LoL) é um jogo multiplayer online battle arena (MOBA) desenvolvido e publicado pela Riot Games. Nele, dois times de cinco jogadores competem em um mapa para destruir a base inimiga, conhecida como Nexus. Cada jogador controla um campeão único com habilidades e estilos de jogo distintos.',
        link: 'https://pt.wikipedia.org/wiki/League_of_Legends',
        loja: 'https://www.leagueoflegends.com/pt-br/',
        anoLancamento: '2009',
        tags: 'Campeões Itens Estratégias Comunidade Riot',
    },
    {
        nome: 'Minecraft',
        descricao: 'Minecraft é um jogo de construção em mundo aberto de alta liberdade, desenvolvido pelo programador sueco Markus "Notch" Persson e posteriormente pela Mojang Studios. Os jogadores podem explorar mundos gerados proceduralmente, compostos por blocos tridimensionais, e interagir com eles de diversas formas, como minerar, construir, explorar e lutar.',
        link: 'https://pt.wikipedia.org/wiki/Minecraft',
        loja: 'https://www.minecraft.net/',
        anoLancamento: '2011',
        tags: 'Criatividade Exploração Sobrevivência Blocos Comunidade',
    },
    {
        nome: 'GTA V',
        descricao: 'Grand Theft Auto V (GTA V) é um jogo de mundo aberto desenvolvido pela Rockstar North. O jogo se passa na fictícia cidade de Los Santos, baseada em Los Angeles, e segue as histórias de três protagonistas enquanto se envolvem em assaltos e outras missões criminosas.',
        link: 'https://pt.wikipedia.org/wiki/Grand_Theft_Auto_V',
        loja: 'https://www.rockstargames.com/V/',
        anoLancamento: '2013',
        tags: 'Mundo Aberto Multi-protagonista Realismo Criminalidade Humor Online Customização Diversidade',
    },
    {
        nome: 'Roblox',
        descricao: 'O Roblox é uma plataforma online que permite que você crie seus próprios jogos e explore milhões de outros criados por uma comunidade global. É como ter um Lego virtual, mas em escala muito maior! Você pode construir mundos, personagens e até mesmo criar suas próprias regras. Além de criar, você também pode explorar uma infinidade de jogos, desde aventuras épicas até simulações de vida real. É um espaço onde a imaginação não tem limites e a diversão é garantida!.',
        link: 'https://pt.wikipedia.org/wiki/Roblox',
        loja: 'https://www.roblox.com/',
        anoLancamento: '2006',
        tags: 'Games Criação Varios jogos ',
    },
    {
        nome: 'God of War Ragnarok',
        descricao: 'God of War Ragnarök é a continuação direta do aclamado jogo de 2018 e marca o ápice da saga nórdica de Kratos e Atreus. A trama se aprofunda nos preparativos para o Ragnarök, o fim dos tempos na mitologia nórdica. Kratos, agora um pai mais protetor, e Atreus, um jovem deus em busca de suas origens, embarcam em uma jornada épica por diversos reinos, enfrentando deuses poderosos e criaturas míticas.',
        link: 'https://pt.wikipedia.org/wiki/God_of_War_Ragnarök',
        loja: 'https://www.playstation.com/pt-br/games/god-of-war-ragnarok/',
        anoLancamento: '2022',
        tags: 'Paternidade Garoto Mitologia Nórdica Mudança Machado Batalhas Batalha Vingança Ghost of Sparta Deus da Guerra Deuses Chefes ',
    },
    {
        nome: 'Assassin\'s Creed Valhalla',
        descricao: 'Assassin\'s Creed Valhalla nos transporta para a era viking, onde encarnamos Eivor, um guerreiro nórdico em busca de um novo lar na Inglaterra. O jogo combina elementos de RPG com a clássica jogabilidade da franquia Assassin\'s Creed, permitindo que exploremos um mundo aberto rico em detalhes, participemos de épicas batalhas e mergulhemos na cultura viking.',
        link: 'https://pt.wikipedia.org/wiki/Assassin%27s_Creed',
        loja: 'https://store.ubisoft.com/pt-br/game/assassins-creed-valhalla',
        anoLancamento: '2007',
        tags: 'Vikings Mitologia Nórdica Exploração Combate Construção Mundo Aberto Batalha Batalhas Chefes',
      },
      {
        nome: 'Warhammer 40,000: Space Marine 2',
        descricao: 'Warhammer 40,000: Space Marine 2 é uma sequência aguardada que coloca os jogadores no papel de um Space Marine, um super-soldado geneticamente modificado, em uma batalha épica contra hordas de alienígenas. O jogo oferece uma experiência de ação frenética em terceira pessoa, com combate visceral e visual deslumbrante, tudo ambientado no universo sombrio e brutal de Warhammer 40K. A história se passa décadas após o primeiro jogo, com o Capitão Titus liderando um novo esquadrão em uma missão para salvar a galáxia.',
        link: 'https://pt.wikipedia.org/wiki/Warhammer_40,000:_Space_Marine_2',
        loja: 'https://store.steampowered.com/app/2183900/Warhammer_40000_Space_Marine_2/',
        anoLancamento: '2023',
        tags: 'Ação frenética Lançamento Warhammer 40K Tecnologia avançada Horda Batalha Batalhas Futurismo Guerra  ',
      },
      {
        nome: 'Palworld',
        descricao: 'Palworld é um jogo que combina elementos de diversos gêneros, oferecendo uma experiência única e envolvente. Imagine um mundo aberto repleto de criaturas encantadoras, semelhantes aos Pokémon, que você pode capturar, treinar e até mesmo fazer trabalhar para você. Além das batalhas e da criação de laços com seus "Pals", o jogo permite que você construa sua própria base, automatize tarefas e explore diversas mecânicas de sobrevivência.',
        link: 'https://pt.wikipedia.org/wiki/Palworld',
        loja: 'https://store.steampowered.com/app/1623730/Palworld/',
        anoLancamento: '2024',
        tags: 'Mundo Aberto Construção Criação  Sobrevivência Chefes Combate Chefes',
      },
      {
        nome: 'Hogwarts Legacy',
        descricao: 'Hogwarts Legacy te convida a mergulhar no universo de Harry Potter como nunca antes! Neste RPG de ação, você assume o papel de um novo estudante de Hogwarts, descobrindo um segredo antigo que ameaça o mundo mágico. Explore o castelo, Hogsmeade e a Floresta Proibida, aprendendo feitiços, criando poções e domando criaturas mágicas. Personalize seu personagem, escolha sua casa e viva a experiência de ser um bruxo ou bruxa, tomando decisões que moldarão o destino do mundo mágico.',
        loja: 'https://www.hogwartslegacy.com/',
        anoLancamento: '2023',
        tags: 'Magia Exploração Personalização História  Imersão Mundo Aberto Liberdade Mistério Chefes ',
      },
      {
        nome: 'God of War',
        descricao: 'God of War (2018) marca um novo capítulo na saga de Kratos, o lendário Deus da Guerra. Abandonando a mitologia grega, o jogo nos leva aos reinos nórdicos, onde Kratos vive em exílio com seu filho, Atreus. Após a morte da esposa, Kratos e Atreus embarcam em uma jornada para espalhar suas cinzas no ponto mais alto dos nove reinos. Essa jornada os levará a enfrentar deuses nórdicos poderosos, criaturas míticas e revelações chocantes sobre o passado de Kratos.',
        link: 'https://pt.wikipedia.org/wiki/God_of_War_(2018)',
        loja: 'https://www.playstation.com/pt-br/games/god-of-war/',
        anoLancamento: '2018',
        tags: 'Paternidade Garoto Mitologia Nórdica Mudança Natureza Machado Batalhas Vinculo Batalha Vingança Ghost of Sparta Deus da Guerra Deuses Chefes',
      },
      {
        nome: 'Counter-Strike: Global Offensive (CS:GO)',
        descricao: 'Counter-Strike: Global Offensive (CS:GO) é um dos jogos de tiro em primeira pessoa (FPS) mais populares do mundo. Nele, duas equipes de cinco jogadores se enfrentam em mapas diversos com objetivos distintos, como plantar ou desarmar bombas e resgatar reféns. O jogo é conhecido por seu ritmo rápido, alta habilidade necessária para se destacar e pela grande comunidade competitiva, que organiza campeonatos com premiações milionárias.',
        link: 'https://pt.wikipedia.org/wiki/Counter-Strike:_Global_Offensive',
        loja: 'https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/',
        anoLancamento: '2012',
        tags: 'Rounds Economia Mapa Rank Estratégia Smoke Flashbang ACE AWP Clutch',
      },
      {
        nome: 'Call of Duty: Warzone',
        descricao: 'Call of Duty: Warzone é um jogo de tiro em primeira pessoa gratuito, desenvolvido pela Infinity Ward e Raven Software. Inserido no universo de Call of Duty: Modern Warfare, Warzone oferece um modo Battle Royale com até 150 jogadores, além de outros modos de jogo como Plunder e Resurgence. O jogo é conhecido por seu ritmo frenético e ação intensa.',
        link: 'https://pt.wikipedia.org/wiki/Call_of_Duty:_Warzone',
        loja: 'https://www.callofduty.com/warzone',
        anoLancamento: '2020',
        tags: 'Battle Royale Tiros  Mapa Grande Free-to-Play Online Multiplayer',
      },
      {
        nome: 'Battlefield 2042',
        descricao: 'Battlefield 2042 é um jogo de tiro em primeira pessoa da franquia Battlefield, desenvolvido pela DICE. O jogo apresenta um mundo em constante evolução, com catástrofes naturais e conflitos globais. O modo multiplayer oferece batalhas épicas com até 128 jogadores em mapas gigantescos.',
        link: 'https://www.ea.com/pt-br/games/battlefield/battlefield-2042',
        loja: 'https://store.origin.com/pt-br/store/battlefield/battlefield-2042',
        anoLancamento: '2021',
        tags: 'Multiplayer Guerra Moderna Veículos Especialistas Destruição ',
      },
      {
        nome: 'Subnautica',
        descricao: 'Subnautica é um jogo de aventura em mundo aberto que te coloca em um planeta oceânico alienígena após um acidente espacial. Sozinho e com recursos limitados, você precisa explorar as profundezas do oceano, construir bases submarinas e sobreviver aos perigos que o aguardam. O jogo combina elementos de sobrevivência, exploração e terror, oferecendo uma experiência única e imersiva. À medida que você desce mais fundo, encontrará criaturas marítimas exóticas, ecossistemas exuberantes e mistérios que desafiarão sua sanidade.',
        link: 'https://pt.wikipedia.org/wiki/Subnautica',
        loja: 'https://store.steampowered.com/app/264710/Subnautica/',
        anoLancamento: '2018',
        tags: 'Sobrevivência Exploração Construção Ambientação Mundo aberto  ',
      },
      {
        nome: 'American Truck Simulator',
        descricao: 'American Truck Simulator é um simulador de caminhoneiro que permite aos jogadores explorar as estradas dos Estados Unidos, entregando cargas e personalizando seus caminhões. O jogo oferece uma experiência realista de direção e gerenciamento de uma empresa de transportes.',
        link: 'https://en.wikipedia.org/wiki/American_Truck_Simulator',
        loja: 'https://store.steampowered.com/app/270880/American_Truck_Simulator/',
        anoLancamento: '2016',
        tags: 'Simulação Caminhões Relaxamento Estados Unidos: ',
      },
];